export type RootStackParamList = {
  Splash: undefined;
  Welcome: undefined;
  Login: undefined;
  Register: undefined;
  ParentLogin: undefined;
  ParentRegister: undefined;
  ForgotPassword: undefined;
  Terms: undefined;
  Home: undefined;
  ParentHome: undefined;
  SuperAdminHome: undefined;
  Onboarding: undefined;
  RegisterSchool: undefined;
  JoinSchool: undefined;
  PendingApproval: undefined;
  ResetPassword: undefined;
  Feature: { title: string } | undefined;
  Students: undefined;
  StudentDetail: { studentId: string; sessionId: string };
  StudentForm: { studentId?: string; sessionId: string };
  Teachers: undefined;
  TeacherEdit: { profileId: string; name: string; phone: string; avatar: string };
  Portal: undefined;
  PortalTerms: { sessionId: string; sessionName: string };
  PortalClasses: { sessionId: string; sessionName: string; termId: string; termName: string };
  ClassDetail: { classId: string; sessionId: string; sessionName: string; termId: string; termName: string };
  Clock: undefined;
  MyClasses: undefined;
  ClassAttendance: { classId: string; sessionId: string; termId: string; className: string };
  ClassResults: { classId: string; sessionId: string; sessionName: string; termId: string; termName: string; className: string };
  ClassReportCards: { classId: string; sessionId: string; sessionName: string; termId: string; termName: string; className: string };
  ReportCardView: { classId: string; sessionId: string; sessionName: string; termId: string; termName: string; className: string } & { studentId: string; studentName: string };
  ClassComments: { classId: string; sessionId: string; sessionName: string; termId: string; termName: string; className: string };
  ClassSubjects: { classId: string; sessionId: string; sessionName: string; termId: string; termName: string; className: string };
  ArrangeSubjects: { classId: string; sessionId: string; sessionName: string; termId: string; termName: string; className: string };
  RemoveFromExam: { classId: string; sessionId: string; sessionName: string; termId: string; termName: string; className: string };
  PublishReports: { classId: string; sessionId: string; sessionName: string; termId: string; termName: string; className: string };
  ClassSettings: { classId: string; sessionId: string; sessionName: string; termId: string; termName: string; className: string } & { arm: string; rawName: string };
  AttendanceSummary: { classId: string; sessionId: string; sessionName: string; termId: string; termName: string; className: string };
  Subjects: undefined;
  AutoComments: undefined;
  ArchivedSessions: undefined;
  Promotion: undefined;
  Migration: undefined;
  SessionsTerms: undefined;
  ReportTemplates: undefined;
  TemplatePreview: { templateKey: string; name: string };
  TemplateCustomize: { templateKey: string; name: string };
  QrCodes: undefined;
  QrPoster: { html: string; name: string };
  SuperAdminVacancy: undefined;
  StaffAttendance: undefined;
  StaffAttendanceDetail: { recordId: string };
  StudentAttendance: undefined;
  SchoolSettings: undefined;
  ClassForm: { sessionId: string; classId?: string; name?: string; arm?: string };
  Developer: undefined;
  Logs: undefined;
  Scan: undefined;
  Location: undefined;
  Push: undefined;
  Pdf: undefined;
  Subscription: undefined;
  ClockFriend: undefined;
  ResultsStatus: undefined;
  ActivityLog: undefined;
  Referral: undefined;
  MyProfile: undefined;
  MySchools: undefined;
  JoinAnotherSchool: undefined;
  Roster: { type?: 'students' | 'staff' } | undefined;
  Announcements: undefined;
  AnnouncementDetail: { id: string };
  AdminAnnouncements: undefined;
  Vacancies: undefined;
  VacancyDetail: { id: string };
  PostVacancy: { editId?: string } | undefined;
  MyVacancies: undefined;
  Events: undefined;
  EventForm: undefined;
  EventDetail: { eventId: string };
  Receipt: { html: string; fileName: string };
  ParentFeeDetail: { eventId: string; studentId: string; studentName: string; schoolId: string };
  ParentReportCard: { studentId: string; studentName: string; schoolId: string; classId: string; termId: string; sessionId: string; sessionName: string; termName: string };
  PaymentCheckout: { kind: 'subscription' | 'fee' | 'vacancy'; url: string; reference: string; paymentId: string; amountLabel?: string };
};
