export type RootStackParamList = {
  Splash: undefined;
  Welcome: undefined;
  Login: undefined;
  Register: undefined;
  ParentLogin: undefined;
  ParentRegister: undefined;
  ForgotPassword: undefined;
  Terms: undefined;
  Home: undefined;
  ParentHome: undefined;
  SuperAdminHome: undefined;
  Onboarding: undefined;
  RegisterSchool: undefined;
  JoinSchool: undefined;
  PendingApproval: undefined;
  ResetPassword: undefined;
  Feature: { title: string } | undefined;
  Developer: undefined;
  Logs: undefined;
  Scan: undefined;
  Location: undefined;
  Push: undefined;
  Pdf: undefined;
};
