export type RootStackParamList = {
  Splash: undefined;
  Welcome: undefined;
  Login: undefined;
  Register: undefined;
  ParentLogin: undefined;
  ParentRegister: undefined;
  ForgotPassword: undefined;
  Terms: undefined;
  Home: undefined;
  ParentHome: undefined;
  SuperAdminHome: undefined;
  Onboarding: undefined;
  RegisterSchool: undefined;
  JoinSchool: undefined;
  PendingApproval: undefined;
  ResetPassword: undefined;
  Feature: { title: string } | undefined;
  Students: undefined;
  StudentDetail: { studentId: string; sessionId: string };
  StudentForm: { studentId?: string; sessionId: string };
  Teachers: undefined;
  TeacherEdit: { profileId: string; name: string; phone: string; avatar: string };
  Portal: undefined;
  PortalTerms: { sessionId: string; sessionName: string };
  PortalClasses: { sessionId: string; sessionName: string; termId: string; termName: string };
  ClassDetail: { classId: string; sessionId: string; sessionName: string; termId: string; termName: string };
  ClassForm: { sessionId: string; classId?: string; name?: string; arm?: string };
  Developer: undefined;
  Logs: undefined;
  Scan: undefined;
  Location: undefined;
  Push: undefined;
  Pdf: undefined;
};
